const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const output = process.env.LAB_DASHBOARD_TEST_OUTPUT || path.resolve(__dirname, '../output/validation/chemicals/browser');
const base = process.env.LAB_DASHBOARD_TEST_BASE_URL || 'http://127.0.0.1:4173/';
(async () => {
  await fs.mkdir(output,{recursive:true});
  const browser=await chromium.launch({headless:true, ...(process.env.LAB_DASHBOARD_BROWSER_CHANNEL ? {channel:process.env.LAB_DASHBOARD_BROWSER_CHANNEL} : {})});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(base);
  const activities=await (await page.request.get(new URL('data/activities.json',base).href)).json();
  assert.equal(activities.length,1276);
  assert.equal(activities.some(activity => activity.id === 'donga_IS2_045' || activity.unit.includes('부록')),false);
  const countLabel=n=>`탐구활동 ${n.toLocaleString('ko')}건`;
  const acidCount=activities.filter(a=>[a.title,a.materials_raw,a.achievement_raw,a.unit,a.publisher_raw].some(s=>String(s??'').includes('염산'))).length;
  await page.getByRole('heading',{name:countLabel(activities.length),exact:true}).waitFor().catch(async error => {
    console.error({pageErrors:errors,body:await page.locator('body').innerText()});
    await page.screenshot({path:path.join(output,'load-failure.png')});
    throw error;
  });
  await page.locator('#search').fill('염산');
  assert.equal(await page.locator('#result-count').innerText(),countLabel(acidCount));
  assert.equal(await page.locator('#chemical-search-results, #active-chemical').count(),0);
  await page.locator('#open-chemicals').click();
  await page.locator('#chemical-search').fill('염산');
  await page.locator('#chemical-results').getByRole('button',{name:'염산',exact:true}).click();
  assert.equal(await page.locator('#chemical-title').innerText(),'염산');
  const acid=await page.locator('#chemical-content').innerText();
  assert.ok(acid.includes('유리마개 사용') && acid.includes('이중 잠금'));
  assert.doesNotMatch(acid, /안전표지|GHS 그림문자|폐기 방법|약품명으로 활동 검색|사용 활동 보기/);
  await page.screenshot({path:path.join(output,'hydrochloric-acid.png')});
  await page.locator('#chemical-close').click();
  assert.equal(await page.locator('#chemical-dialog').isVisible(),false);
  assert.equal(await page.locator('#search').inputValue(),'염산');
  assert.equal(await page.locator('#result-count').innerText(),countLabel(acidCount));
  await page.locator('#reset-filters').click();
  await page.locator('#search').fill('양이 달라져도 변하지 않는 값 찾기');
  await page.locator('[data-activity-id="activity_0001"] .card-actions button').click();
  await page.locator('#activity-dialog').getByRole('button',{name:'에탄올',exact:true}).click();
  assert.equal(await page.locator('#chemical-title').innerText(),'에탄올');
  assert.ok((await page.locator('#chemical-content').innerText()).includes('고무마개를 사용하여 밀봉'));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#activity-dialog').isVisible(),true);
  await page.locator('#close-dialog').click();
  await page.locator('#reset-filters').click();
  await page.locator('#open-chemicals').click();
  assert.equal(await page.locator('#chemical-count').innerText(),'약품 177건');
  await page.locator('#chemical-search').fill('황산 구리(Ⅱ)');
  await page.locator('#chemical-results').getByRole('button',{name:'황산 구리(II)',exact:true}).click();
  assert.equal(await page.locator('#chemical-title').innerText(),'황산 구리(II)');
  await page.locator('#chemical-back').click();
  await page.locator('#chemical-search').fill('페놀프탈레인 용액');
  await page.locator('#chemical-results').getByRole('button',{name:'페놀프탈레인 용액',exact:true}).click();
  const cabinets=page.locator('#chemical-content section').filter({has:page.getByRole('heading',{name:'보관장 분류',exact:true})});
  assert.match(await cabinets.innerText(),/^보관장 분류\s+미확인/);
  assert.equal(await cabinets.locator('.compartment.inactive').count(),6);
  assert.equal(await cabinets.locator('.current').count(),0);
  await page.locator('#chemical-back').click();
  await page.locator('#chemical-search').fill('에탄올');
  await page.locator('#chemical-results').getByRole('button',{name:'에탄올',exact:true}).click();
  assert.doesNotMatch(await page.locator('#chemical-content').innerText(), /약품명으로 활동 검색|사용 활동 보기/);
  await page.locator('#chemical-close').click();
  assert.equal(await page.locator('#chemical-dialog').isVisible(),false);
  assert.equal(await page.locator('#result-count').innerText(),countLabel(activities.length));
  await page.locator('#open-chemicals').click();
  await page.getByRole('button',{name:'공통 관리 안내',exact:true}).click();
  assert.equal(await page.locator('#chemical-title').innerText(),'약품 공통 관리 안내');
  assert.ok((await page.locator('#chemical-content').innerText()).includes('폐수'));
  assert.equal(await page.locator('.cabinet-map .compartment:not(.inactive)').count(),6);
  assert.equal(await page.locator('.waste-flow .waste-result').count(),4);
  assert.match(await page.locator('.waste-flow').innerText(), /암모니아 함유폐수/);
  await page.locator('#chemical-back').click();
  await page.locator('#chemical-search').fill('확인되지않은약품000');
  assert.equal(await page.locator('#chemical-count').innerText(),'약품 0건');
  assert.ok((await page.locator('#chemical-results').innerText()).includes('미확인'));
  await page.locator('#chemical-search').fill('');
  await page.screenshot({path:path.join(output,'catalogue.png')});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(output,'catalogue-mobile.png')});
  assert.deepEqual(errors,[]);
  await browser.close();
  const report={status:'passed',checked:['plain activity search without chemical suggestions or filter','source storage rules','activity to chemical modal and Escape','catalogue and normalized notation search','conflicting cabinet stays unknown','chemical details without activity search buttons','shared guidance','unmatched unknown','mobile layout'],pageErrors:errors};
  await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
