const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const output = process.env.LAB_DASHBOARD_TEST_OUTPUT || path.resolve(__dirname, '../output/validation');
const base = process.env.LAB_DASHBOARD_TEST_BASE_URL || 'http://127.0.0.1:4173/';
const key = 'science-classroom-prep.preferences.v1';

(async () => {
  await fs.mkdir(output,{recursive:true});
  const browser = await chromium.launch({headless:true, ...(process.env.LAB_DASHBOARD_BROWSER_CHANNEL ? {channel:process.env.LAB_DASHBOARD_BROWSER_CHANNEL} : {})});
  const errors=[];
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  let page=await context.newPage();
  page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(base);
  await page.waitForFunction(()=>document.getElementById('result-count').textContent==='탐구활동 862건');
  assert.equal(await page.locator('.activity-card').count(),30);
  assert.equal(await page.locator('#sort-order').inputValue(),'achievement');
  assert.equal(await page.locator('#sort-order option[value="source"]').count(),0);
  const activities = await (await page.request.get(new URL('data/activities.json',base).href)).json();
  const achievements = await (await page.request.get(new URL('data/achievements.json',base).href)).json();
  const linkedIds = items => [...new Set(items.map(activity => activity.achievement_id).filter(Boolean))].sort();
  const optionIds = async () => (await page.locator('#achievement-filter option').evaluateAll(options => options.slice(1).map(option => option.value))).sort();
  const expectedOrder = [...activities].sort((a,b) => (a.achievement_raw?.match(/^\d+-\d+/)?.[0] ?? '999-999').localeCompare(b.achievement_raw?.match(/^\d+-\d+/)?.[0] ?? '999-999', 'en', {numeric:true})
    || a.publisher_raw.localeCompare(b.publisher_raw,'ko') || a.source_row-b.source_row);
  while (await page.locator('#load-more').isVisible()) await page.locator('#load-more').click();
  assert.deepEqual(await page.locator('.activity-card').evaluateAll(cards=>cards.map(card=>card.dataset.activityId)),expectedOrder.map(activity=>activity.id));
  await page.locator('#sort-order').selectOption('title');
  await page.locator('#reset-filters').click();
  assert.equal(await page.locator('#sort-order').inputValue(),'achievement');
  assert.deepEqual(await page.locator('.activity-card').evaluateAll(cards=>cards.map(card=>card.dataset.activityId)),expectedOrder.slice(0,30).map(activity=>activity.id));
  await page.evaluate(key => localStorage.setItem(key, JSON.stringify({publishers:['동아','미래앤','비상','천재(임성숙)','천재(정대홍)'],classes:3,students:10,groupSize:4})), key);
  await page.reload();
  await page.waitForFunction(()=>document.getElementById('result-count').textContent==='탐구활동 862건');
  assert.equal(await page.locator('#materials-tab, #materials-view, #select-results, [data-select-activity]').count(),0);
  assert.ok(!await page.locator('body').innerText().then(text=>text.includes('교과서 대조 미확인')));
  for(const publisher of ['동아','미래앤','천재(임성숙)','천재(정대홍)','지학사','YBM']) await page.locator(`input[data-publisher="${publisher}"]`).uncheck();
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 111건');
  assert.deepEqual(await page.locator('.activity-card').evaluateAll(cards=>cards.map(card=>card.dataset.activityId)),expectedOrder.filter(activity=>activity.publisher_raw==='비상').slice(0,30).map(activity=>activity.id));
  assert.equal(await page.locator('#settings-toggle, #settings-panel, #class-count, #students-per-class, #students-per-group').count(),0);
  const stored=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
  assert.deepEqual(stored.publishers,['비상']);
  assert.deepEqual(Object.keys(stored),['publishers','publisherCatalog']);
  assert.equal(Object.hasOwn(stored,'selected'),false);
  await page.reload();
  await page.waitForFunction(()=>document.getElementById('result-count').textContent==='탐구활동 111건');
  assert.equal(await page.locator('input[data-publisher="비상"]').isChecked(),true);
  await page.close();
  page=await context.newPage();
  page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(base);
  await page.waitForFunction(()=>document.getElementById('result-count').textContent==='탐구활동 111건');
  await page.locator('#reset-filters').click();
  const unitNumbers = async () => (await page.locator('#unit-filter option').allTextContents()).slice(1).filter(text => /^\d+/.test(text)).map(text => Number(text.match(/^\d+/)[0]));
  const achievementNumbers = async () => (await page.locator('#achievement-filter option').allTextContents()).slice(1).map(text => text.match(/^\d+-\d+/)[0]);
  const groupNumbers = async () => (await page.locator('#achievement-filter optgroup').evaluateAll(groups => groups.map(group => group.label))).filter(text => /^\d+\./.test(text)).map(text => Number(text.match(/^\d+/)[0]));
  const unitValue = async number => page.locator('#unit-filter option').evaluateAll((options, number) => options.find(option => Number(option.textContent.match(/^\d+/)?.[0]) === number).value, number);
  assert.deepEqual(await page.locator('#grade-filter option').evaluateAll(options => options.map(option => option.value)), ['all','1','2','3']);
  assert.deepEqual(await unitNumbers(), Array.from({length:15}, (_, i) => i + 1));
  assert.deepEqual(await groupNumbers(), Array.from({length:23}, (_, i) => i + 1));
  assert.deepEqual(await optionIds(), linkedIds(activities));
  assert.equal(achievements.length, 87);
  const allStandards = await achievementNumbers();
  assert.equal(allStandards.length, 87);
  assert.deepEqual(allStandards, [...allStandards].sort((a,b) => a.localeCompare(b, 'en', {numeric:true})));
  assert.ok(!(await page.locator('#achievement-filter').innerText()).includes('9과'));
  await page.locator('#grade-filter').selectOption('1');
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 328건');
  assert.deepEqual(await unitNumbers(), [1,2,3,4,5,6,7,8]);
  assert.deepEqual(await groupNumbers(), [1,2,3,4,5,6,7,8]);
  assert.deepEqual(await optionIds(), linkedIds(activities.filter(activity => activity.grade === 1)));
  const firstUnit = await unitValue(1);
  await page.locator('#unit-filter').selectOption(firstUnit);
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 8건');
  assert.deepEqual(await achievementNumbers(), ['1-1','1-2','1-3']);
  await page.locator('#achievement-filter').selectOption({index:1});
  const firstAchievement = await page.locator('#achievement-filter').inputValue();
  await page.locator('#grade-filter').selectOption('all');
  assert.equal(await page.locator('#unit-filter').inputValue(),firstUnit);
  assert.equal(await page.locator('#achievement-filter').inputValue(),firstAchievement);
  await page.locator('#grade-filter').selectOption('2');
  assert.equal(await page.locator('#unit-filter').inputValue(),'all');
  assert.equal(await page.locator('#achievement-filter').inputValue(),'all');
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 446건');
  assert.deepEqual(await unitNumbers(), [9,10,11,12,13,14,15]);
  assert.deepEqual(await groupNumbers(), [8,9,10,11,12,13,14,15]);
  assert.deepEqual(await optionIds(), linkedIds(activities.filter(activity => activity.grade === 2)));
  await page.locator('#unit-filter').selectOption(await unitValue(9));
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 44건');
  assert.deepEqual(await achievementNumbers(), ['9-1','9-2','9-3','9-4','9-5']);
  await page.locator('#achievement-filter').selectOption({index:1});
  await page.locator('#grade-filter').selectOption('1');
  assert.equal(await page.locator('#unit-filter').inputValue(),'all');
  assert.equal(await page.locator('#achievement-filter').inputValue(),'all');
  await page.locator('#unit-filter').selectOption(await unitValue(8));
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 45건');
  const sharedId = linkedIds(activities.filter(activity => activity.grade === 1))
    .find(id => activities.some(activity => activity.grade === 2 && activity.achievement_id === id));
  assert.ok(sharedId);
  const sharedGradeTwoUnit = activities.find(activity => activity.grade === 2 && activity.achievement_id === sharedId).unit;
  await page.locator('#grade-filter').selectOption('2');
  await page.locator('#unit-filter').selectOption(sharedGradeTwoUnit);
  assert.ok((await optionIds()).includes(sharedId));
  await page.locator('#achievement-filter').selectOption(sharedId);
  assert.equal(await page.locator('#result-count').innerText(),
    `탐구활동 ${activities.filter(activity => activity.grade === 2 && activity.unit === sharedGradeTwoUnit && activity.achievement_id === sharedId).length}건`);
  await page.locator('#reset-filters').click();
  await page.locator('#search').fill('염산');
  assert.ok(await page.locator('.activity-card').count()>0);
  for(const text of await page.locator('.activity-card').allTextContents()) assert.ok(text.includes('염산'));
  await page.locator('#search').fill('아무결과없는검색어000');
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 0건');
  await page.locator('#reset-filters').click();
  await page.locator('#achievement-filter').selectOption({index:1});
  const compareCount=await page.locator('.activity-card').count();
  assert.ok(compareCount>0);
  assert.equal(await page.locator('#active-achievement').isVisible(),true);
  await page.screenshot({path:path.join(output,'achievement-comparison.png')});
  const detailId = await page.locator('.activity-card').first().getAttribute('data-activity-id');
  const detailActivity = activities.find(a => a.id === detailId);
  const displayItems = items => items == null ? '미확인' : items.length ? items.join(', ') : '해당 항목 없음';
  await page.locator('.card-actions button').first().click();
  assert.equal(await page.locator('#activity-dialog').isVisible(),true);
  assert.equal(await page.locator('#dialog-select').count(),0);
  assert.equal(await page.locator('#activity-dialog').getByRole('button',{name:'닫기',exact:true}).count(),1);
  await page.screenshot({path:path.join(output,'activity-detail.png')});
  assert.doesNotMatch(await page.locator('#dialog-content').innerText(), /준비 수량|교과서 수량|설정에 따른 수량/);
  assert.deepEqual(await page.locator('#dialog-content .dialog-section h3').allTextContents(), ['실험 기자재', '실험 준비물', '약품 관리']);
  assert.equal(await page.locator('#dialog-content .dialog-section').nth(0).locator('p').innerText(), displayItems(detailActivity.equipment));
  assert.equal(await page.locator('#dialog-content .dialog-section').nth(1).locator('p').innerText(), displayItems(detailActivity.supplies));
  assert.ok(!(await page.locator('#dialog-content').innerText()).includes('교과서 대조'));
  await page.keyboard.press('Escape');
  await page.locator('#reset-filters').click();
  await page.locator('#grade-filter').selectOption('3');
  assert.equal(await page.locator('#result-count').innerText(), '탐구활동 88건');
  assert.deepEqual(await groupNumbers(), [16,17,18,19,20,21,22,23]);
  assert.deepEqual(await optionIds(), linkedIds(activities.filter(activity => activity.grade === 3)));
  assert.ok((await page.locator('.publisher-tag').allTextContents()).every(text => text === 'YBM'));
  await page.locator('#reset-filters').click();
  // Check actual category values for added books, missing lists, and empty categories.
  const examples = [activities.find(a => a.id.startsWith('jihaksa_') && a.equipment?.length && a.supplies?.length),
    activities.find(a => a.grade === 3 && a.supplies?.length),
    activities.find(a => a.materials_raw == null), activities.find(a => a.supplies?.length === 0)];
  for (const activity of examples) {
    assert.ok(activity);
    await page.locator('#search').fill(activity.title);
    await page.locator(`[data-activity-id="${activity.id}"] .card-actions button`).click();
    assert.deepEqual(await page.locator('#dialog-content .raw-materials').allTextContents(),
      [displayItems(activity.equipment), displayItems(activity.supplies)]);
    await page.locator('#close-dialog').click();
  }
  for (const activity of [
    activities.find(a => a.id.startsWith('jihaksa_') && a.achievement_id),
    activities.find(a => a.id.startsWith('jihaksa_') && a.achievement_id == null),
  ]) {
    assert.ok(activity);
    await page.locator('#search').fill(activity.title);
    await page.locator(`[data-activity-id="${activity.id}"] .card-actions button`).click();
    assert.equal(await page.locator('#dialog-content dd').nth(4).innerText(), activity.achievement_raw ?? '미확인');
    assert.doesNotMatch(await page.locator('#dialog-content').innerText(), /9과\d{2}-\d{2}|scope_based|candidate|교과서 대조/);
    await page.locator('#close-dialog').click();
  }
  await page.locator('#reset-filters').click();
  for(const publisher of [...new Set(activities.map(a=>a.publisher_raw))]) await page.locator(`input[data-publisher="${publisher}"]`).uncheck();
  assert.equal(await page.locator('#result-count').innerText(),'탐구활동 0건');
  await page.reload();
  await page.waitForFunction(()=>document.getElementById('result-count').textContent==='탐구활동 0건');
  await page.locator('#reset-filters').click();
  await page.screenshot({path:path.join(output,'desktop.png')});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(output,'mobile.png')});
  const blocked=await browser.newContext();
  await blocked.addInitScript(()=>{Object.defineProperty(Storage.prototype,'setItem',{value(){throw new DOMException('Blocked','SecurityError')}})});
  const blockedPage=await blocked.newPage();
  await blockedPage.goto(base);
  await blockedPage.waitForFunction(()=>document.getElementById('result-count').textContent==='탐구활동 862건');
  await blockedPage.locator('input[data-publisher="비상"]').uncheck();
  assert.equal(await blockedPage.locator('#storage-warning').isVisible(),true);
  assert.equal(await blockedPage.locator('#result-count').innerText(),'탐구활동 751건');
  const failed=await browser.newContext();
  await failed.route('**/data/activities.json*',route=>route.fulfill({status:500,body:'unavailable'}));
  const failedPage=await failed.newPage();
  await failedPage.goto(base);
  await failedPage.getByRole('button',{name:'다시 불러오기'}).waitFor();
  assert.equal(errors.length,0,errors.join('\n'));
  await browser.close();
  const report={status:'passed',checked:['source data load','publisher filter','classroom controls and quantity displays removed','localStorage reload and new tab','preparation list controls removed','grade mapping and unit boundary','linked grade, unit and achievement filters','numeric unit and achievement ordering','incompatible filter reset and compatible selection retention','material and chemical query','no results','achievement comparison','linked and unconfirmed detail text','detail modal and Escape','empty publisher selection persistence','desktop and mobile layout','storage denied graceful failure','data-load error'],pageErrors:errors};
  await fs.writeFile(path.join(output,'browser-report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
